### PR TITLE
:construction_worker: [maykinmedia/objects-api#463] Add trivy image scan

### PR DESCRIPTION
**Pull request by stevenbal**
Fixes maykinmedia/objects-api#463 partially

### CODE REVIEW

**Comment by stevenbal** [comment]
I'll add it to the other components once this PR is merged

**Review by annashamray — COMMENTED** [review]
In ON PR I can see that the workflow was successfully completed (inluding the uploading to Security tab part), but I can't find the results there: 
https://github.com/open-zaak/open-notificaties/security/code-scanning/tools/Trivy/status 
It looks like the last results were in September. Do I look in the incorrect place?

**Comment by stevenbal** [comment]
@annashamray hmm strange, maybe it only shows results for main/master?

**Review by annashamray — APPROVED** [review]
Ok, let's then merge this PR and the ON PR and see if security tab is updated

**Comment by stevenbal** [comment]
ugh it still seems to be raising issues, I'll have to add https://github.com/open-formulieren/open-forms/blob/22d641bb16b4cab03b8ccdfb66efa332dc3b3a15/.github/workflows/trivy.yml#L11 probably as well to avoid this

**Pull request merged**
